// `npm run docs`: writes docs/TOOLS.md and docs/COMMANDS.md from the running server itself, so they are always exact.
//   --check   writes nothing; fails if the files on disk differ from what the server says now (used by npm run check)
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import { root } from "./azgaar.mjs";

const check = process.argv.includes("--check");
const work = mkdtempSync(join(tmpdir(), "azgaar-docs-"));
const base = JSON.parse(readFileSync(join(root, "config", "fmg-mcp.json"), "utf8"));
base.browser.headless = true;
if (process.env.FMG_TEST_CHROMIUM) {
  base.browser.executablePath = process.env.FMG_TEST_CHROMIUM;
  base.browser.channel = null;
} else base.browser.channel = process.env.FMG_TEST_CHANNEL ?? base.browser.channel;
base.browser.args = (process.env.FMG_TEST_ARGS ?? "").split(",").filter(Boolean);
base.map.seed = "333";
base.server.port = 0;
base.allowEval = true; // so that map_eval is documented too
base.startup = "new";
const configFile = join(work, "config.json");
writeFileSync(configFile, JSON.stringify(base));

const esc = s => String(s ?? "").replace(/\|/g, "\\|").replace(/\r?\n+/g, " ").trim();

function typeOf(schema) {
  if (!schema) return "any";
  if (schema.enum) return `one of: ${schema.enum.map(v => `\`${v}\``).join(", ")}`;
  if (schema.anyOf) return [...new Set(schema.anyOf.map(typeOf))].join(" or ");
  if (schema.type === "array") return `list of ${typeOf(schema.items)}`;
  if (schema.type === "object") {
    const keys = Object.keys(schema.properties ?? {});
    return keys.length ? `object {${keys.join(", ")}}` : "object";
  }
  const range = [schema.minimum !== undefined ? `min ${schema.minimum}` : "", schema.maximum !== undefined ? `max ${schema.maximum}` : ""].filter(Boolean).join(", ");
  return `${schema.type ?? "any"}${range ? ` (${range})` : ""}`;
}

function paramsTable(properties = {}, required = []) {
  const names = Object.keys(properties);
  if (!names.length) return "_No parameters._\n";
  const rows = names.map(n => `| \`${n}\` | ${esc(typeOf(properties[n]))} | ${required.includes(n) ? "yes" : "no"} | ${esc(properties[n].description)} |`);
  return `| Parameter | Type | Required | Meaning |\n|---|---|---|---|\n${rows.join("\n")}\n`;
}

const transport = new StdioClientTransport({
  command: process.execPath,
  args: [join(root, "scripts", "start.mjs")],
  env: { ...process.env, FMG_CONFIG: configFile, FMG_MAPS_DIR: join(work, "maps"), FMG_PROFILE_DIR: join(work, "profile") },
  stderr: "pipe"
});
const client = new Client({ name: "docs", version: "0" });
let tools;
let commands;
try {
  await client.connect(transport);
  tools = (await client.listTools()).tools;
  const reply = await client.callTool({ name: "map_commands", arguments: {} });
  commands = JSON.parse(reply.content.find(p => p.type === "text").text);
} finally {
  await client.close().catch(() => {});
  rmSync(work, { recursive: true, force: true });
}

const header = "<!-- Generated by `npm run docs` from the running server. Do not edit by hand: change the code, then run it again. -->\n";

const toolsDoc = [
  header,
  "# Tools reference\n",
  "Every tool the MCP server offers, with its parameters. Your AI program shows these to the model automatically; this page is for people. `map_eval` is only present when `allowEval` is on (see [CONFIGURATION](CONFIGURATION.md)).\n",
  "| Tool | What it is for |\n|---|---|",
  ...tools.map(t => `| [\`${t.name}\`](#${t.name}) | ${esc(t.title ?? "")} |`),
  "",
  ...tools.flatMap(t => [`## ${t.name}\n`, `${t.description ?? ""}\n`, paramsTable(t.inputSchema?.properties, t.inputSchema?.required ?? [])])
].join("\n");

const spec = p => `${typeOf(p.enum ? { enum: p.enum } : { type: p.type === "integer" ? "integer" : p.type, minimum: p.min, maximum: p.max })}`;
const specTable = params => {
  const names = Object.keys(params ?? {});
  if (!names.length) return "_No parameters._\n";
  return `| Parameter | Type | Required | Meaning |\n|---|---|---|---|\n${names.map(n => `| \`${n}\` | ${esc(spec(params[n]))} | ${params[n].required ? "yes" : "no"} | ${esc(params[n].description)} |`).join("\n")}\n`;
};

const commandsDoc = [
  header,
  "# Edit commands and selection shapes\n",
  "These are the arguments of `map_apply` (edit commands) and `map_select` (selection shapes). The same list is returned by the `map_commands` tool.\n",
  "## Edit commands (`map_apply`)\n",
  "| Command | What it does |\n|---|---|",
  ...commands.commands.map(c => `| [\`${c.name}\`](#${c.name.toLowerCase()}) | ${esc(c.description).slice(0, 110)}${esc(c.description).length > 110 ? "..." : ""} |`),
  "",
  ...commands.commands.flatMap(c => [`### ${c.name}\n`, `${c.description}\n`, specTable(c.params)]),
  "## Selection shapes (`map_select`)\n",
  "| Shape | What it selects |\n|---|---|",
  ...Object.entries(commands.shapes).map(([n, s]) => `| [\`${n}\`](#shape-${n}) | ${esc(s.description)} |`),
  "",
  ...Object.entries(commands.shapes).flatMap(([n, s]) => [`### shape-${n}\n`, `${s.description}\n`, specTable(s.params)]),
  "## Selection options (all shapes)\n",
  specTable(commands.selectOptions)
].join("\n");

const outputs = [
  [join(root, "docs", "TOOLS.md"), `${toolsDoc}\n`],
  [join(root, "docs", "COMMANDS.md"), `${commandsDoc}\n`]
];
let stale = 0;
for (const [file, content] of outputs) {
  if (check) {
    const now = existsSync(file) ? readFileSync(file, "utf8").replace(/\r\n/g, "\n") : "";
    if (now !== content) {
      stale += 1;
      console.error(`docs out of date: ${file} (run: npm run docs)`);
    }
  } else {
    mkdirSync(join(root, "docs"), { recursive: true });
    writeFileSync(file, content);
    console.log(`wrote ${file}`);
  }
}
if (check) console.log(stale ? `\n${stale} generated doc(s) out of date` : "generated docs are up to date");
process.exit(stale ? 1 : 0);
